# This is a basic workflow to help you get started with Actions

name: PrimeDAO CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  [push, PR]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Runs a single command using the runners shell
      - name: Installs needed packages using npm
        run: npm i

  lint:
    runs-on: ubuntu-latest

    needs: build

      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

        # Runs a single command using the runners shell
      - name: Installs needed packages using npm
        run: npm i

        # Runs a single command using the runners shell
      - name: Lints the project
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    needs: build

      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'


        # Runs a single command using the runners shell
      - name: Installs needed packages using npm
        run: npm i

        # Runs a single command using the runners shell
      - name: Tests the project
        run: npm run test

  coverage:
    runs-on: ubuntu-latest

    needs: test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

        # Runs a single command using the runners shell
      - name: Installs needed packages using npm
        run: npm i && npm install -g codecov

        # Runs a single command using the runners shell
      - name: Tests the project
        run: npm run coverage


      # Runs a single command using the runners shell
      - name: Tests the project
        run: codecov
    env:
      CODECOV_TOKEN: 'e07e4cc4-7393-4325-b1d1-cb53f7346b05'


